npm install @neondatabase/neon-js

psql postgresql://mytest_owner:Bvbh6LgkJV8R@ep-fancy-bonus-a8xl2bvb-pooler.eastus2.azure.neon.tech/mytest?sslmode=require&channel_binding=require

connetURL: https://ep-fancy-bonus-a8xl2bvb.apirest.eastus2.azure.neon.tech/mytest/rest/v1
projectId: tight-darkness-73979208
projectName: mytest
mytest-apikey:napi_a6bbxxbrsjrx63r95h69us48npf01wavzbnw1zkps8ilwcum1qqmml42z85n6bn6
user-apiKey:napi_065q8k1wkvem2c5nbfdstc7bvhqlwjs3cvynmj3pj5jp6q992m2mf8tsui1h18sk


import { neon } from '@neondatabase/serverless';

// Neon Console > Connect 에서 복사한 연결 문자열을 여기에 넣으세요
const DATABASE_URL = 'postgresql://mytest_owner:Bvbh6LgkJV8R@ep-fancy-bonus-a8xl2bvb-pooler.eastus2.azure.neon.tech/mytest?sslmode=require&channel_binding=require';

const sql = neon(DATABASE_URL);

// posts 테이블에서 데이터 조회
const data = await sql`
    SELECT * FROM posts
    WHERE 1=1
    ORDER BY created_at DESC
`;

console.log(data);

 

-- 1. Create the table
CREATE TABLE posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  content text NOT NULL,
  is_published boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
-- 2. Enable RLS
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
-- 3. Read published posts
CREATE POLICY read_published_posts ON posts
FOR SELECT TO authenticated
USING (is_published = true);
-- 4. Full access to own posts
CREATE POLICY manage_own_posts ON posts
FOR ALL TO authenticated
USING (auth.user_id() = user_id)
WITH CHECK (auth.user_id() = user_id);